default: &default
  adapter: postgresql
  encoding: unicode
  username: crist
  password: jakec6560
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: whats_new_development

test:
  <<: *default
  database: whats_new_test

production:
  <<: *default
  database: whats_new_production
